am_blog_article_overview:
    path: /admin/articles/
    defaults: { _controller: am.controller.article::overviewAction }

am_blog_article_edit:
    path: /admin/articles/edit/{slug}
    defaults: { _controller: am.controller.article::editAction }
