bm_blog_article_view:
    path: /article/{slug}
    defaults: { _controller: SeerUK\Module\BlogModule\Controller\ArticleController::viewAction }
    requirements:
        id: \d+

# bm_blog_edit:
#     path: /edit/{id}
#     defaults: { _controller: SeerUK\Module\BlogModule\Controller\BlogController::editAction }
#     requirements:
#         id: \d+
