bm_blog_view:
    path: /view/{id}
    defaults: { _controller: SeerUK\Module\BlogModule\Controller\BlogController::viewAction }
    requirements:
        id: \d+

bm_blog_edit:
    path: /edit/{id}
    defaults: { _controller: SeerUK\Module\BlogModule\Controller\BlogController::editAction }
    requirements:
        id: \d+
