sm_authentication_login:
    path: /account/login
    defaults: { _controller: SeerUK\Module\SecurityModule\Controller\AuthenticationController::loginAction }

sm_authentication_logout:
    path: /account/logout
    defaults: { _controller: SeerUK\Module\SecurityModule\Controller\AuthenticationController::logoutAction }
