seeruk_admin:
    resource: "../../src/SeerUK/Module/AdminModule/module/config/routes.yml"
    prefix: /

seeruk_api:
    resource: "../../src/SeerUK/Module/ApiModule/module/config/routes.yml"
    prefix: /

seeruk_blog:
    resource: "../../src/SeerUK/Module/BlogModule/module/config/routes.yml"
    prefix: /

seeruk_security:
    resource: "../../src/SeerUK/Module/SecurityModule/module/config/routes.yml"
    prefix: /
